spring:
  application:
    name: student
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME_EMAIL}
    password: ${PASSWORD_EMAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
server:
  port: 8080
app:
  welcome-text: Hello World, this message from Spring Boot
  timezone: Asia/Jakarta
  currency: IDR
  secret-key: ${SECRET_KEY}
  expired-ms: 3600000 
---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:${DB_URL_DEV}
    username: ${DB_USERNAME_DEV}
    password: ${DB_PASSWORD_DEV}
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      format-sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
app:
  welcome-text: Hello World, this message from development
---
spring:
  config:
    activate:
      on-profile: staging
app:
  welcome-text: Hello World, this message from staging
---
spring:
  datasource:
    url: jdbc:${DB_URL_PROD}
    username: ${DB_USERNAME_PROD}
    password: ${DB_PASSWORD_PROD}
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      format-sql: true
    show-sql: true
  config:
   activate:
    on-profile: production
app:
 welcome-text: ${WELCOME_TEXT}
 currency: ${CURRENCY}
